In [2]:
import pandas as pd
import yfinance as yf

In [3]:
ticker_symbol = 'AAPL'

aapl = yf.Ticker(ticker_symbol)

historical_data = aapl.history(period='1Y')

In [4]:
financials = aapl.financials

In [5]:
aapl.income_stmt

,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.147,0.162,0.133,0.144
Normalized EBITDA,129188000000.0,133138000000.0,123136000000.0,81020000000.0
Net Income From Continuing Operation Net Minority Interest,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Reconciled Depreciation,11519000000.0,11104000000.0,11284000000.0,11056000000.0
Reconciled Cost Of Revenue,214137000000.0,223546000000.0,212981000000.0,169559000000.0
EBITDA,129188000000.0,133138000000.0,123136000000.0,81020000000.0
EBIT,117669000000.0,122034000000.0,111852000000.0,69964000000.0
Net Interest Income,-183000000.0,-106000000.0,198000000.0,890000000.0
Interest Expense,3933000000.0,2931000000.0,2645000000.0,2873000000.0
Interest Income,3750000000.0,2825000000.0,2843000000.0,3763000000.0
Normalized Income,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income From Continuing And Discontinued Operation,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Total Expenses,268984000000.0,274891000000.0,256868000000.0,208227000000.0
Total Operating Income As Reported,114301000000.0,119437000000.0,108949000000.0,66288000000.0
Diluted Average Shares,15812547000.0,16325819000.0,16864919000.0,17528214000.0
Basic Average Shares,15744231000.0,16215963000.0,16701272000.0,17352119000.0
Diluted EPS,6.13,6.11,5.61,3.28
Basic EPS,6.16,6.15,5.67,3.31
Diluted NI Availto Com Stockholders,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income Common Stockholders,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income Including Noncontrolling Interests,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income Continuous Operations,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Tax Provision,16741000000.0,19300000000.0,14527000000.0,9680000000.0
Pretax Income,113736000000.0,119103000000.0,109207000000.0,67091000000.0
Other Income Expense,-382000000.0,-228000000.0,60000000.0,-87000000.0
Other Non Operating Income Expenses,-382000000.0,-228000000.0,60000000.0,-87000000.0
Net Non Operating Interest Income Expense,-183000000.0,-106000000.0,198000000.0,890000000.0
Interest Expense Non Operating,3933000000.0,2931000000.0,2645000000.0,2873000000.0
Interest Income Non Operating,3750000000.0,2825000000.0,2843000000.0,3763000000.0
Operating Income,114301000000.0,119437000000.0,108949000000.0,66288000000.0
Operating Expense,54847000000.0,51345000000.0,43887000000.0,38668000000.0
Research And Development,29915000000.0,26251000000.0,21914000000.0,18752000000.0
Selling General And Administration,24932000000.0,25094000000.0,21973000000.0,19916000000.0
Gross Profit,169148000000.0,170782000000.0,152836000000.0,104956000000.0
Cost Of Revenue,214137000000.0,223546000000.0,212981000000.0,169559000000.0
Total Revenue,383285000000.0,394328000000.0,365817000000.0,274515000000.0
Operating Revenue,383285000000.0,394328000000.0,365817000000.0,274515000000.0

In [6]:
aapl.get_income_stmt()

,2023-09-30,2022-09-30,2021-09-30,2020-09-30
TaxEffectOfUnusualItems,0.0,0.0,0.0,0.0
TaxRateForCalcs,0.147,0.162,0.133,0.144
NormalizedEBITDA,129188000000.0,133138000000.0,123136000000.0,81020000000.0
NetIncomeFromContinuingOperationNetMinorityInterest,96995000000.0,99803000000.0,94680000000.0,57411000000.0
ReconciledDepreciation,11519000000.0,11104000000.0,11284000000.0,11056000000.0
ReconciledCostOfRevenue,214137000000.0,223546000000.0,212981000000.0,169559000000.0
EBITDA,129188000000.0,133138000000.0,123136000000.0,81020000000.0
EBIT,117669000000.0,122034000000.0,111852000000.0,69964000000.0
NetInterestIncome,-183000000.0,-106000000.0,198000000.0,890000000.0
InterestExpense,3933000000.0,2931000000.0,2645000000.0,2873000000.0
InterestIncome,3750000000.0,2825000000.0,2843000000.0,3763000000.0
NormalizedIncome,96995000000.0,99803000000.0,94680000000.0,57411000000.0
NetIncomeFromContinuingAndDiscontinuedOperation,96995000000.0,99803000000.0,94680000000.0,57411000000.0
TotalExpenses,268984000000.0,274891000000.0,256868000000.0,208227000000.0
TotalOperatingIncomeAsReported,114301000000.0,119437000000.0,108949000000.0,66288000000.0
DilutedAverageShares,15812547000.0,16325819000.0,16864919000.0,17528214000.0
BasicAverageShares,15744231000.0,16215963000.0,16701272000.0,17352119000.0
DilutedEPS,6.13,6.11,5.61,3.28
BasicEPS,6.16,6.15,5.67,3.31
DilutedNIAvailtoComStockholders,96995000000.0,99803000000.0,94680000000.0,57411000000.0
NetIncomeCommonStockholders,96995000000.0,99803000000.0,94680000000.0,57411000000.0
NetIncome,96995000000.0,99803000000.0,94680000000.0,57411000000.0
NetIncomeIncludingNoncontrollingInterests,96995000000.0,99803000000.0,94680000000.0,57411000000.0
NetIncomeContinuousOperations,96995000000.0,99803000000.0,94680000000.0,57411000000.0
TaxProvision,16741000000.0,19300000000.0,14527000000.0,9680000000.0
PretaxIncome,113736000000.0,119103000000.0,109207000000.0,67091000000.0
OtherIncomeExpense,-382000000.0,-228000000.0,60000000.0,-87000000.0
OtherNonOperatingIncomeExpenses,-382000000.0,-228000000.0,60000000.0,-87000000.0
NetNonOperatingInterestIncomeExpense,-183000000.0,-106000000.0,198000000.0,890000000.0
InterestExpenseNonOperating,3933000000.0,2931000000.0,2645000000.0,2873000000.0
InterestIncomeNonOperating,3750000000.0,2825000000.0,2843000000.0,3763000000.0
OperatingIncome,114301000000.0,119437000000.0,108949000000.0,66288000000.0
OperatingExpense,54847000000.0,51345000000.0,43887000000.0,38668000000.0
ResearchAndDevelopment,29915000000.0,26251000000.0,21914000000.0,18752000000.0
SellingGeneralAndAdministration,24932000000.0,25094000000.0,21973000000.0,19916000000.0
GrossProfit,169148000000.0,170782000000.0,152836000000.0,104956000000.0
CostOfRevenue,214137000000.0,223546000000.0,212981000000.0,169559000000.0
TotalRevenue,383285000000.0,394328000000.0,365817000000.0,274515000000.0
OperatingRevenue,383285000000.0,394328000000.0,365817000000.0,274515000000.0

In [7]:
aapl.cashflow

,2023-09-30,2022-09-30,2021-09-30,2020-09-30,2019-09-30
Free Cash Flow,99584000000.0,111443000000.0,92953000000.0,73365000000.0,NaN
Repurchase Of Capital Stock,-77550000000.0,-89402000000.0,-85971000000.0,-72358000000.0,NaN
Repayment Of Debt,-11151000000.0,-9543000000.0,-8750000000.0,-12629000000.0,NaN
Issuance Of Debt,5228000000.0,5465000000.0,20393000000.0,16091000000.0,NaN
Issuance Of Capital Stock,NaN,NaN,1105000000.0,880000000.0,781000000.0
Capital Expenditure,-10959000000.0,-10708000000.0,-11085000000.0,-7309000000.0,NaN
Interest Paid Supplemental Data,3803000000.0,2865000000.0,2687000000.0,3002000000.0,NaN
Income Tax Paid Supplemental Data,18679000000.0,19573000000.0,25385000000.0,9501000000.0,NaN
End Cash Position,30737000000.0,24977000000.0,35929000000.0,39789000000.0,NaN
Beginning Cash Position,24977000000.0,35929000000.0,39789000000.0,50224000000.0,NaN
Changes In Cash,5760000000.0,-10952000000.0,-3860000000.0,-10435000000.0,NaN
Financing Cash Flow,-108488000000.0,-110749000000.0,-93353000000.0,-86820000000.0,NaN
Cash Flow From Continuing Financing Activities,-108488000000.0,-110749000000.0,-93353000000.0,-86820000000.0,NaN
Net Other Financing Charges,-6012000000.0,-6383000000.0,-5580000000.0,-2880000000.0,NaN
Cash Dividends Paid,-15025000000.0,-14841000000.0,-14467000000.0,-14081000000.0,NaN
Common Stock Dividend Paid,-15025000000.0,-14841000000.0,-14467000000.0,-14081000000.0,NaN
Net Common Stock Issuance,-77550000000.0,-89402000000.0,-85971000000.0,-72358000000.0,NaN
Common Stock Payments,-77550000000.0,-89402000000.0,-85971000000.0,-72358000000.0,NaN
Common Stock Issuance,NaN,NaN,1105000000.0,880000000.0,781000000.0
Net Issuance Payments Of Debt,-9901000000.0,-123000000.0,12665000000.0,2499000000.0,NaN
Net Short Term Debt Issuance,-3978000000.0,3955000000.0,1022000000.0,-963000000.0,NaN
Net Long Term Debt Issuance,-5923000000.0,-4078000000.0,11643000000.0,3462000000.0,NaN
Long Term Debt Payments,-11151000000.0,-9543000000.0,-8750000000.0,-12629000000.0,NaN
Long Term Debt Issuance,5228000000.0,5465000000.0,20393000000.0,16091000000.0,NaN
Investing Cash Flow,3705000000.0,-22354000000.0,-14545000000.0,-4289000000.0,NaN
Cash Flow From Continuing Investing Activities,3705000000.0,-22354000000.0,-14545000000.0,-4289000000.0,NaN
Net Other Investing Changes,-1337000000.0,-2086000000.0,-385000000.0,-909000000.0,NaN
Net Investment Purchase And Sale,16001000000.0,-9560000000.0,-3075000000.0,5453000000.0,NaN
Sale Of Investment,45514000000.0,67363000000.0,106483000000.0,120391000000.0,NaN
Purchase Of Investment,-29513000000.0,-76923000000.0,-109558000000.0,-114938000000.0,NaN
Net Business Purchase And Sale,NaN,-306000000.0,-33000000.0,-1524000000.0,-624000000.0
Purchase Of Business,NaN,-306000000.0,-33000000.0,-1524000000.0,-624000000.0
Net PPE Purchase And Sale,-10959000000.0,-10708000000.0,-11085000000.0,-7309000000.0,NaN
Purchase Of PPE,-10959000000.0,-10708000000.0,-11085000000.0,-7309000000.0,NaN
Operating Cash Flow,110543000000.0,122151000000.0,104038000000.0,80674000000.0,NaN
Cash Flow From Continuing Operating Activities,110543000000.0,122151000000.0,104038000000.0,80674000000.0,NaN
Change In Working Capital,-6577000000.0,1200000000.0,-4911000000.0,5690000000.0,NaN
Change In Other Working Capital,NaN,478000000.0,1676000000.0,2081000000.0,-625000000.0
Change In Other Current Liabilities,3031000000.0,6110000000.0,7475000000.0,8916000000.0,NaN
Change In Other Current Assets,-5684000000.0,-6499000000.0,-8042000000.0,-9588000000.0,NaN
Change In Payables And Accrued Expense,-1889000000.0,9448000000.0,12326000000.0,-4062000000.0,NaN
Change In Payable,-1889000000.0,9448000000.0,12326000000.0,-4062000000.0,NaN
Change In Account Payable,-1889000000.0,9448000000.0,12326000000.0,-4062000000.0,NaN
Change In Inventory,-1618000000.0,1484000000.0,-2642000000.0,-127000000.0,NaN
Change In Receivables,-417000000.0,-9343000000.0,-14028000000.0,8470000000.0,NaN
Changes In Account Receivables,-1688000000.0,-1823000000.0,-10125000000.0,6917000000.0,NaN
Other Non Cash Items,-2227000000.0,1006000000.0,-4921000000.0,-97000000.0,NaN
Stock Based Compensation,10833000000.0,9038000000.0,7906000000.0,6829000000.0,NaN
Deferred Tax,NaN,895000000.0,-4774000000.0,-215000000.0,-340000000.0
Deferred Income Tax,NaN,895000000.0,-4774000000.0,-215000000.0,-340000000.0
Depreciation Amortization Depletion,11519000000.0,11104000000.0,11284000000.0,11056000000.0,NaN
Depreciation And Amortization,11519000000.0,11104000000.0,11284000000.0,11056000000.0,NaN
Net Income From Continuing Operations,96995000000.0,99803000000.0,94680000000.0,57411000000.0,NaN

In [8]:
aapl.recommendations_summary

  period  strongBuy  buy  hold  sell  strongSell
0     0m         11   21     6     0           0
1    -1m         12   23    10     1           0
2    -2m         12   21    10     1           0
3    -3m         10   24     7     1           0

In [9]:
aapl.upgrades_downgrades

                                    Firm         ToGrade   FromGrade Action
GradeDate
2024-09-25 14:27:12  New Street Research         Neutral     Neutral   reit
2024-09-24 09:42:31              Needham             Buy         Buy   reit
2024-09-19 10:41:39              Needham             Buy         Buy   reit
2024-09-16 16:00:10   Evercore ISI Group      Outperform  Outperform   reit
2024-09-10 15:48:17            JP Morgan      Overweight  Overweight   main
...                                  ...             ...         ...    ...
2014-09-30 10:00:21            Jefferies            Hold               init
2014-09-10 13:00:00             Barclays      Overweight               main
2014-09-10 12:00:00          Wells Fargo  Market Perform               main
2014-09-10 09:59:13        Goldman Sachs             Buy               main
2012-09-12 11:51:00        Hudson Square             Buy               main

[970 rows x 4 columns]

In [10]:
aapl.earnings_estimate

     numberOfAnalysts   avg   low  high  yearAgoEps  growth
0q                 26  1.60  1.53  1.65        1.36   0.176
+1q                20  2.39  2.21  2.61        2.18   0.096
0y                 41  6.70  6.57  6.76        5.73   0.169
+1y                41  7.48  6.88  8.00        6.70   0.116

In [11]:
aapl.revenue_estimate

,numberOfAnalysts,avg,low,high,yearAgoRevenue,growth
0q,25,94410100000,93653000000,97945300000,83600100000,0.129
+1q,19,128424000000,123883000000,133406000000,111695000000,0.150
0y,39,390372000000,387118000000,394050000000,358027000000,0.090
+1y,39,421688000000,401691000000,441882000000,390372000000,0.080

In [12]:
aapl.eps_trend

     current  7daysAgo  30daysAgo  60daysAgo  90daysAgo
0q      1.60      1.60       1.59       1.55       1.54
+1q     2.39      2.39       2.39       2.38       2.34
0y      6.70      6.70       6.70       6.61       6.59
+1y     7.48      7.48       7.48       7.34       7.29

In [13]:
aapl.earnings_history

            epsEstimate  epsActual  epsDifference  surprisePercent
2023-09-30         1.30       1.36           0.06            0.046
2023-12-31         2.10       2.18           0.08            0.038
2024-03-31         1.50       1.53           0.03            0.020
2024-06-30         1.35       1.40           0.05            0.037

In [14]:
aapl.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2025-07-30 06:00:00-04:00           NaN           NaN          NaN
2025-04-30 06:00:00-04:00           NaN           NaN          NaN
2025-01-30 16:00:00-05:00           NaN           NaN          NaN
2024-10-31 06:00:00-04:00          1.60           NaN          NaN
2024-08-01 16:00:00-04:00          1.35          1.40       0.0399
2024-05-02 16:00:00-04:00          1.50          1.53       0.0197
2024-02-01 16:00:00-05:00          2.10          2.18       0.0390
2023-11-02 16:00:00-04:00          1.39          1.46       0.0492
2023-08-03 16:00:00-04:00          1.19          1.26       0.0549
2023-05-04 16:00:00-04:00          1.43          1.52       0.0603
2023-02-02 16:00:00-05:00          1.94          1.88      -0.0288
2022-10-27 16:00:00-04:00          1.27          1.29       0.0155

In [15]:
start_date, end_date = '2017-01-01', '2024-07-31'
aapl_history = yf.download('AAPL', start=start_date, end=end_date)

[*********************100%***********************]  1 of 1 completed

In [16]:
aapl_history

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2017-01-03,28.950001,29.082500,28.690001,29.037500,26.921547,115127600
2017-01-04,28.962500,29.127501,28.937500,29.004999,26.891415,84472400
2017-01-05,28.980000,29.215000,28.952499,29.152500,27.028172,88774400
2017-01-06,29.195000,29.540001,29.117500,29.477501,27.329493,127007600
2017-01-09,29.487499,29.857500,29.485001,29.747499,27.579807,134247600
...,...,...,...,...,...,...
2024-07-24,224.000000,224.800003,217.130005,218.539993,218.287323,61777600
2024-07-25,218.929993,220.850006,214.619995,217.490005,217.238556,51391200
2024-07-26,218.699997,219.490005,216.009995,217.960007,217.708008,41601300
2024-07-29,216.960007,219.300003,215.750000,218.240005,217.987686,36311800
2024-07-30,219.190002,220.330002,216.119995,218.800003,218.547043,41643800